### ISSUE TITLE
wrong parsing in gephi?

### ISSUE THREAD

**Issue by ysagon** [cyberang3l/InfiniBand-Graphviz-ualization#1]
I have tried your script, the conversion seems to run well, but I have some problem to display the result using Gephi.

It seems that Gephi parses the header of the file infiniband.topo.dot as nodes.

![gephi_2016-10-24_16-43-15](https://cloud.githubusercontent.com/assets/1266022/19650287/06fa9ac4-9a09-11e6-9f54-3f55d25a08a9.png)

dot - graphviz version 2.38.0 (20140413.2041)
Gephi 0.9.1 201510222201

**Comment by cyberang3l** [comment]
Hi, thanks for reporting this bug. I'll look into that!

**Comment by cyberang3l** [comment]
This used to be working fine, but I guess that either something has changed in the latest version of graphviz or the Gephi dot file parser (or both).

In any case, it looks like dot-file support in Gephi is very limited: https://gephi.org/users/supported-graph-formats/ so I added a new option `--export-gexf` to the script that allows it to export a GEXF file that is fully supported by Gephi.
