### ISSUE TITLE
Add hostname as node label

### ISSUE THREAD

**Issue by richard-mansfield** [cyberang3l/InfiniBand-Graphviz-ualization#4]
It would be good to have an option to include the hostname into the node's label if it's present in the input file.

```
289a290
>                     topology[current_node]['label'] = r.groups[3]
400c401
<             node_node = et.SubElement(nodes_node, 'node', attrib = {'id': node.name, 'label': node.name})
---
>             node_node = et.SubElement(nodes_node, 'node', attrib = {'id': node.name, 'label': topology[node.name]['label']})
```

**Comment by cyberang3l** [comment]
Haven't played with InfiniBand topologies for a while. How does a file that includes node names look like?
Do you have a sample file with node names you can share with me?

**Comment by richard-mansfield** [comment]
Here's an example IB topology file that includes node names.  Using the patch above, we can easily select nodes using the label.

[example-with-label.txt.gz](https://github.com/cyberang3l/InfiniBand-Graphviz-ualization/files/4995954/example-with-label.txt.gz)

**Comment by alexandrestein** [comment]
Hello,

Any chances to see this implemented at some point ?

**Comment by cyberang3l** [comment]
Should be working now!

![Screenshot_20240211_020950](https://github.com/cyberang3l/InfiniBand-Graphviz-ualization/assets/5658474/417d13c3-a5bb-48fd-9fcb-46e3a8e4b991)
