### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by lukexijn** [cyberang3l/InfiniBand-Graphviz-ualization#6]
./InfiniBand-graphviz.py -f infiniband.topo
report  -bash: ./InfiniBand-graphviz.py: No such file or directory
in fact ,InfiniBand-graphviz.py and infiniband.topo in the same dir
and infiniband.topo form ibnetdiscover > infiniband.topo
any issure ,bro

**Comment by cyberang3l** [comment]
That's a user error: `report -bash: ./InfiniBand-graphviz.py: No such file or directory`

You obviously mistype something there (filenames are case-sensitive).

Try to run this with the python3 interpreter.
